version: "3"
services:
  nucat-react-prod:
    image: nucat-react-prod:v1.0
    stdin_open: true
    ports:
      - "8000:80"
    environment:
      NODE_ENV: production
    networks:
      - nucat-mern
  nucat-node:
    image: nucat-node:v1.0
    ports:
      - "3000:3000"
    env_file: ./server/.env
    networks:
      - nucat-mern
networks:
  nucat-mern:
    driver: bridge
